feat(core): supprt role
chrononeko/chronocat pull request #2
Opened 2023-08-26 15:56 UTC by Hieuzest

2023-08-26 16:00 UTC, MicroCBer requested changes

2023-08-26 16:00 UTC, MicroCBer commented on packages/core/src/server/index.ts
Please separate this into a single file to make it more clear

2023-08-26 16:08 UTC, Hieuzest commented
Known issue: For some reason, one have to first click to enter any group window to activate the logic. This might be a problem when using autologin.

2023-08-26 17:04 UTC, MicroCBer commented
I've seen that you modified the uixConvert cache service and added group member role info into the convert function, instead of making it a separate route as an API. IMO it should be a separate API, as the uixConvert would be executed for really many times, so it shouldn't contain some really costly code.

2023-08-26 17:08 UTC, MicroCBer commented
Also it feels strange to write some code to add extra info other than uid <-> uix convert in uix convert class

2023-08-26 17:14 UTC, MicroCBer commented on packages/core/src/index.ts
> +              .map(
Probably it's better to just add some code here to handle member-role-related logic rather than reusing uixConvert ones.

2023-08-26 17:18 UTC, Hieuzest commented on packages/core/src/index.ts
> +              .map(
ja. i feel i should add two functions before and after uixConvert to make use of that internal delay?

2023-08-26 17:21 UTC, Hieuzest commented
Also, i don't feel there really is a place to natively storing role. Is it ok to use that field or should we add extra field to red protocol?

2023-08-26 17:43 UTC, MicroCBer commented on packages/core/src/index.ts
> +              .map(
it should be placed before uix convert preprocess for future compatibility reasons

2023-08-26 17:45 UTC, MicroCBer commented
I felt it's ok to add it here as it's really a commonly used information. Also, have you checked the original JSON? It's really seems strange to me that this piece of information is not included in the original Message object

2023-08-26 17:55 UTC, Hieuzest commented on packages/core/src/index.ts
> +              .map(
The point is that both uix and role need small delay to wait for response, we shouldn't put extra delay.

2023-08-26 18:02 UTC, MicroCBer reviewed
huh, I didn't get it, Why invoke prepare role before preprocess and fill role after it

2023-08-26 18:07 UTC, Hieuzest commented
invoke `getMemberInfo` returns nothing but `onMemberInfoChange`

2023-08-27 04:14 UTC, MicroCBer approved these changes

2023-08-27 04:14 UTC, MicroCBer commented
LGTM

2023-08-27 09:58 UTC, ilharp approved these changes

2023-08-27 09:58 UTC, merged